// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProjekat17172.Models;

namespace WebProjekat17172.Migrations
{
    [DbContext(typeof(AmbulanteContext))]
    [Migration("20210815160557_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebProjekat17172.Models.Ambulanta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojSati")
                        .HasColumnType("int")
                        .HasColumnName("BrojSati");

                    b.Property<int>("BrojTerminaPoSatu")
                        .HasColumnType("int")
                        .HasColumnName("BrojTerminaPoSatu");

                    b.Property<string>("Naziv")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Naziv");

                    b.Property<int>("PocetakRada")
                        .HasColumnType("int")
                        .HasColumnName("PocetakRada");

                    b.HasKey("ID");

                    b.ToTable("Ambulanta");
                });

            modelBuilder.Entity("WebProjekat17172.Models.Ljubimac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojCipa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BrojCipa");

                    b.Property<string>("DatumRodjenja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DatumRodjenja");

                    b.Property<string>("Ime")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Ime");

                    b.Property<string>("JMBGVlasnika")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("JMBGVlasnika");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Pol");

                    b.Property<string>("Vrsta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vrsta");

                    b.HasKey("ID");

                    b.ToTable("Ljubimac");
                });

            modelBuilder.Entity("WebProjekat17172.Models.Termin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AmbulantaID")
                        .HasColumnType("int");

                    b.Property<int?>("LjubimacID")
                        .HasColumnType("int");

                    b.Property<int>("Minuti")
                        .HasColumnType("int")
                        .HasColumnName("Minuti");

                    b.Property<int>("Sati")
                        .HasColumnType("int")
                        .HasColumnName("Sati");

                    b.Property<int?>("VeterinarID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AmbulantaID");

                    b.HasIndex("LjubimacID");

                    b.HasIndex("VeterinarID");

                    b.ToTable("Termin");
                });

            modelBuilder.Entity("WebProjekat17172.Models.Veterinar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AmbulantaID")
                        .HasColumnType("int");

                    b.Property<string>("DatumRodjenja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DatumRodjenja");

                    b.Property<string>("Ime")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Ime");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Pol");

                    b.Property<string>("Prezime")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Prezime");

                    b.Property<string>("PutanjaDoSlike")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PutanjaDoSlike");

                    b.Property<string>("StrucnaSprema")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StrucnaSprema");

                    b.HasKey("ID");

                    b.HasIndex("AmbulantaID");

                    b.ToTable("Veterinar");
                });

            modelBuilder.Entity("WebProjekat17172.Models.Termin", b =>
                {
                    b.HasOne("WebProjekat17172.Models.Ambulanta", "Ambulanta")
                        .WithMany("Termini")
                        .HasForeignKey("AmbulantaID");

                    b.HasOne("WebProjekat17172.Models.Ljubimac", "Ljubimac")
                        .WithMany()
                        .HasForeignKey("LjubimacID");

                    b.HasOne("WebProjekat17172.Models.Veterinar", "Veterinar")
                        .WithMany()
                        .HasForeignKey("VeterinarID");

                    b.Navigation("Ambulanta");

                    b.Navigation("Ljubimac");

                    b.Navigation("Veterinar");
                });

            modelBuilder.Entity("WebProjekat17172.Models.Veterinar", b =>
                {
                    b.HasOne("WebProjekat17172.Models.Ambulanta", "Ambulanta")
                        .WithMany("Veterinari")
                        .HasForeignKey("AmbulantaID");

                    b.Navigation("Ambulanta");
                });

            modelBuilder.Entity("WebProjekat17172.Models.Ambulanta", b =>
                {
                    b.Navigation("Termini");

                    b.Navigation("Veterinari");
                });
#pragma warning restore 612, 618
        }
    }
}
